name: Options Wheel Strategy Automation

on:
  schedule:
    # 10:00 AM ET → 14:00 UTC
    - cron: '0 14 * * 1-5'
    # 1:00 PM ET  → 17:00 UTC
    - cron: '0 17 * * 1-5'
    # 3:30 PM ET → 19:30 UTC
    - cron: '30 19 * * 1-5'
  workflow_dispatch:

jobs:
  wheel:
    runs-on: ubuntu-latest
    # … your env, setup steps …

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Record last log filename
        id: before
        run: |
          mkdir -p logs
          last=$(ls -t logs/trades_*.json 2>/dev/null | head -n1 || echo "")
          echo "before=$last" >> $GITHUB_OUTPUT

      - name: Run strategy
        run: run-strategy --strat-log --log-level INFO --fresh-start

      - name: Record new log filename
        id: after
        run: |
          last=$(ls -t logs/trades_*.json 2>/dev/null | head -n1 || echo "")
          echo "after=$last" >> $GITHUB_OUTPUT

      - name: Send trades to Google Sheets
        if: steps.after.outputs.after != steps.before.outputs.before
        run: |
          file="${{ steps.after.outputs.after }}"
          curl -X POST -H "Content-Type: application/json" \
               --data-binary "@$file" \
               "$GOOGLE_SCRIPT_URL"

      - name: Commit JSON logs
        if: steps.after.outputs.after != steps.before.outputs.before
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add logs/*.json
          if ! git diff --cached --quiet; then
            git commit -m "chore: add new trade log"
            git push
          fi
